# Generated by Django 4.0.6 on 2022-08-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_appointment_alter_contect_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TextField(),
        ),
    ]
