# Generated by Django 4.0.6 on 2022-08-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_appointment_data_alter_appointment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='address',
            new_name='Appointment_address',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='data',
            new_name='Appointment_data',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='message',
            new_name='Appointment_message',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='name',
            new_name='Appointment_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='email',
            new_name='Appointment_name_email',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='Appointment_time',
        ),
    ]
