# Generated by Django 4.0.6 on 2022-08-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_address_appointment_appointment_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Appointment_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Appointment_data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Appointment_name_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Appointment_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Appointment_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Appointment_time',
            new_name='time',
        ),
    ]
